In [98]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('E:/accepted_2007_to_2018Q4.csv',low_memory=False)

In [10]:
df_copy = df.copy()

In [11]:
df_copy.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_copy.shape

(2260701, 151)

In [13]:
list(df_copy)

['id',
 'member_id',
 'loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'term',
 'int_rate',
 'installment',
 'grade',
 'sub_grade',
 'emp_title',
 'emp_length',
 'home_ownership',
 'annual_inc',
 'verification_status',
 'issue_d',
 'loan_status',
 'pymnt_plan',
 'url',
 'desc',
 'purpose',
 'title',
 'zip_code',
 'addr_state',
 'dti',
 'delinq_2yrs',
 'earliest_cr_line',
 'fico_range_low',
 'fico_range_high',
 'inq_last_6mths',
 'mths_since_last_delinq',
 'mths_since_last_record',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'revol_util',
 'total_acc',
 'initial_list_status',
 'out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'last_pymnt_d',
 'last_pymnt_amnt',
 'next_pymnt_d',
 'last_credit_pull_d',
 'last_fico_range_high',
 'last_fico_range_low',
 'collections_12_mths_ex_med',
 'mths_since_last_major_derog',
 'policy_code',
 'application_type',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'open_acc_6m',
 'open_act_il',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'total_bal_il',
 'il_util',
 'open_rv_12m',
 'open_rv_24m',
 'max_bal_bc',
 'all_util',
 'total_rev_hi_lim',
 'inq_fi',
 'total_cu_tl',
 'inq_last_12m',
 'acc_open_past_24mths',
 'avg_cur_bal',
 'bc_open_to_buy',
 'bc_util',
 'chargeoff_within_12_mths',
 'delinq_amnt',
 'mo_sin_old_il_acct',
 'mo_sin_old_rev_tl_op',
 'mo_sin_rcnt_rev_tl_op',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_bc',
 'mths_since_recent_bc_dlq',
 'mths_since_recent_inq',
 'mths_since_recent_revol_delinq',
 'num_accts_ever_120_pd',
 'num_actv_bc_tl',
 'num_actv_rev_tl',
 'num_bc_sats',
 'num_bc_tl',
 'num_il_tl',
 'num_op_rev_tl',
 'num_rev_accts',
 'num_rev_tl_bal_gt_0',
 'num_sats',
 'num_tl_120dpd_2m',
 'num_tl_30dpd',
 'num_tl_90g_dpd_24m',
 'num_tl_op_past_12m',
 'pct_tl_nvr_dlq',
 'percent_bc_gt_75',
 'pub_rec_bankruptcies',
 'tax_liens',
 'tot_hi_cred_lim',
 'total_bal_ex_mort',
 'total_bc_limit',
 'total_il_high_credit_limit',
 'revol_bal_joint',
 'sec_app_fico_range_low',
 'sec_app_fico_range_high',
 'sec_app_earliest_cr_line',
 'sec_app_inq_last_6mths',
 'sec_app_mort_acc',
 'sec_app_open_acc',
 'sec_app_revol_util',
 'sec_app_open_act_il',
 'sec_app_num_rev_accts',
 'sec_app_chargeoff_within_12_mths',
 'sec_app_collections_12_mths_ex_med',
 'sec_app_mths_since_last_major_derog',
 'hardship_flag',
 'hardship_type',
 'hardship_reason',
 'hardship_status',
 'deferral_term',
 'hardship_amount',
 'hardship_start_date',
 'hardship_end_date',
 'payment_plan_start_date',
 'hardship_length',
 'hardship_dpd',
 'hardship_loan_status',
 'orig_projected_additional_accrued_interest',
 'hardship_payoff_balance_amount',
 'hardship_last_payment_amount',
 'disbursement_method',
 'debt_settlement_flag',
 'debt_settlement_flag_date',
 'settlement_status',
 'settlement_date',
 'settlement_amount',
 'settlement_percentage',
 'settlement_term']

In [14]:
df_copy['loan_status']

0           Fully Paid
1           Fully Paid
2           Fully Paid
3              Current
4           Fully Paid
              ...
2260696        Current
2260697    Charged Off
2260698        Current
2260699            NaN
2260700            NaN
Name: loan_status, Length: 2260701, dtype: object

In [15]:
df_copy['loan_status'].value_counts()

Fully Paid                                             1076751
Current                                                 878317
Charged Off                                             268559
Late (31-120 days)                                       21467
In Grace Period                                           8436
Late (16-30 days)                                         4349
Does not meet the credit policy. Status:Fully Paid        1988
Does not meet the credit policy. Status:Charged Off        761
Default                                                     40
Name: loan_status, dtype: int64

In [16]:
df_copy['loan_status'].replace(['Does not meet the credit policy. Status:Fully Paid','Does not meet the credit policy. Status:Charged Off'],['Fully Paid','Charged Off'],inplace=True)

In [62]:
df_copy['loan_status'].value_counts(normalize=True)*100

Fully Paid     80.021646
Charged Off    19.978354
Name: loan_status, dtype: float64

In [63]:
df_copy['loan_status']

0           Fully Paid
1           Fully Paid
2           Fully Paid
4           Fully Paid
5           Fully Paid
              ...
2260688     Fully Paid
2260690     Fully Paid
2260691    Charged Off
2260692     Fully Paid
2260697    Charged Off
Name: loan_status, Length: 1348059, dtype: object

In [35]:
df_copy = df_copy[df_copy['loan_status'].isin(['Fully Paid','Charged Off'])]

In [44]:
# df_copy[(df_copy['loan_status']=='Fully Paid') | (df_copy['loan_status']=='Charged Off')]

In [45]:
# x = df_copy['loan_status'].isin(['Fully Paid','Charged Off'])

In [46]:
# df_copy[x]

In [47]:
df_copy.shape

(1348059, 151)

In [50]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [65]:
len(df_copy)

1348059

In [76]:
drop_nan = df_copy.isna().sum()

In [79]:
drop_nan

id                                                  0
member_id                                     1348059
loan_amnt                                           0
funded_amnt                                         0
funded_amnt_inv                                     0
term                                                0
int_rate                                            0
installment                                         0
grade                                               0
sub_grade                                           0
emp_title                                       85944
emp_length                                      78545
home_ownership                                      0
annual_inc                                          4
verification_status                                 0
issue_d                                             0
loan_status                                         0
pymnt_plan                                          0
url                                                 0
desc                                          1222104
purpose                                             0
title                                           16661
zip_code                                            1
addr_state                                          0
dti                                               374
delinq_2yrs                                        29
earliest_cr_line                                   29
fico_range_low                                      0
fico_range_high                                     0
inq_last_6mths                                     30
mths_since_last_delinq                         679942
mths_since_last_record                        1118644
open_acc                                           29
pub_rec                                            29
revol_bal                                           0
revol_util                                        897
total_acc                                          29
initial_list_status                                 0
out_prncp                                           0
out_prncp_inv                                       0
total_pymnt                                         0
total_pymnt_inv                                     0
total_rec_prncp                                     0
total_rec_int                                       0
total_rec_late_fee                                  0
recoveries                                          0
collection_recovery_fee                             0
last_pymnt_d                                     2325
last_pymnt_amnt                                     0
next_pymnt_d                                  1345310
last_credit_pull_d                                 57
last_fico_range_high                                0
last_fico_range_low                                 0
collections_12_mths_ex_med                        145
mths_since_last_major_derog                    994309
policy_code                                         0
application_type                                    0
annual_inc_joint                              1322259
dti_joint                                     1322262
verification_status_joint                     1322464
acc_now_delinq                                     29
tot_coll_amt                                    70276
tot_cur_bal                                     70276
open_acc_6m                                    810462
open_act_il                                    810461
open_il_12m                                    810461
open_il_24m                                    810461
mths_since_rcnt_il                             824677
total_bal_il                                   810461
il_util                                        883043
open_rv_12m                                    810461
open_rv_24m                                    810461
max_bal_bc                                     810461
all_util                                       810514
total_rev_hi_lim                                70276
inq_fi                                         810461
total_cu_tl                                    810462
inq_last_12m                                   810462
acc_open_past_24mths                            50030
avg_cur_bal                                     70298
bc_open_to_buy                                  63892
bc_util                                         64661
chargeoff_within_12_mths                          145
delinq_amnt                                        29
mo_sin_old_il_acct                             108324
mo_sin_old_rev_tl_op                            70277
mo_sin_rcnt_rev_tl_op                           70277
mo_sin_rcnt_tl                                  70276
mort_acc                                        50030
mths_since_recent_bc                            62970
mths_since_recent_bc_dlq                      1029039
mths_since_recent_inq                          176820
mths_since_recent_revol_delinq                 898097
num_accts_ever_120_pd                           70276
num_actv_bc_tl                                  70276
num_actv_rev_tl                                 70276
num_bc_sats                                     58590
num_bc_tl                                       70276
num_il_tl                                       70276
num_op_rev_tl                                   70276
num_rev_accts                                   70277
num_rev_tl_bal_gt_0                             70276
num_sats                                        58590
num_tl_120dpd_2m                               120150
num_tl_30dpd                                    70276
num_tl_90g_dpd_24m                              70276
num_tl_op_past_12m                              70276
pct_tl_nvr_dlq                                  70430
percent_bc_gt_75                                64304
pub_rec_bankruptcies                             1365
tax_liens                                         105
tot_hi_cred_lim                                 70276
total_bal_ex_mort                               50030
total_bc_limit                                  50030
total_il_high_credit_limit                      70276
revol_bal_joint                               1329430
sec_app_fico_range_low                        1329429
sec_app_fico_range_high                       1329429
sec_app_earliest_cr_line                      1329429
sec_app_inq_last_6mths                        1329429
sec_app_mort_acc                              1329429
sec_app_open_acc                              1329429
sec_app_revol_util                            1329757
sec_app_open_act_il                           1329429
sec_app_num_rev_accts                         1329429
sec_app_chargeoff_within_12_mths              1329429
sec_app_collections_12_mths_ex_med            1329429
sec_app_mths_since_last_major_derog           1341414
hardship_flag                                       0
hardship_type                                 1342305
hardship_reason                               1342305
hardship_status                               1342305
deferral_term                                 1342305
hardship_amount                               1342305
hardship_start_date                           1342305
hardship_end_date                             1342305
payment_plan_start_date                       1342305
hardship_length                               1342305
hardship_dpd                                  1342305
hardship_loan_status                          1342305
orig_projected_additional_accrued_interest    1344300
hardship_payoff_balance_amount                1342305
hardship_last_payment_amount                  1342305
disbursement_method                                 0
debt_settlement_flag                                0
debt_settlement_flag_date                     1314773
settlement_status                             1314773
settlement_date                               1314773
settlement_amount                             1314773
settlement_percentage                         1314773
settlement_term                               1314773
dtype: int64

In [84]:
drop_nan = drop_nan[drop_nan.values>len(df_copy)*0.10]

In [93]:
drop_nan.index

Index(['member_id', 'desc', 'mths_since_last_delinq', 'mths_since_last_record', 'next_pymnt_d', 'mths_since_last_major_derog', 'annual_inc_joint', 'dti_joint', 'verification_status_joint', 'open_acc_6m', 'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util', 'inq_fi', 'total_cu_tl', 'inq_last_12m', 'mths_since_recent_bc_dlq', 'mths_since_recent_inq', 'mths_since_recent_revol_delinq', 'revol_bal_joint', 'sec_app_fico_range_low', 'sec_app_fico_range_high', 'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths', 'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util', 'sec_app_open_act_il', 'sec_app_num_rev_accts', 'sec_app_chargeoff_within_12_mths', 'sec_app_collections_12_mths_ex_med', 'sec_app_mths_since_last_major_derog', 'hardship_type', 'hardship_reason', 'hardship_status', 'deferral_term', 'hardship_amount', 'hardship_start_date', 'hardship_end_date', 'payment_plan_start_date',
       'hardship_length', 'hardship_dpd', 'hardship_loan_status', 'orig_projected_additional_accrued_interest', 'hardship_payoff_balance_amount', 'hardship_last_payment_amount', 'debt_settlement_flag_date', 'settlement_status', 'settlement_date', 'settlement_amount', 'settlement_percentage', 'settlement_term'],
      dtype='object')

In [97]:
df_copy.drop(labels=drop_nan.index,inplace=True,axis=1)

C:\Users\avitr\AppData\Local\Temp\ipykernel_14192\2224360886.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy.drop(labels=drop_nan.index,inplace=True,axis=1)

In [99]:
df_copy.shape

(1348059, 92)

In [100]:
df_copy.head()

,id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag
0,68407277,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.0,Aug-2003,675.0,679.0,1.0,7.0,0.0,2765.0,29.7,13.0,w,0.0,0.0,4421.723917,4421.72,3600.0,821.72,0.0,0.0,0.0,Jan-2019,122.67,Mar-2019,564.0,560.0,0.0,1.0,Individual,0.0,722.0,144904.0,9300.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,N,Cash,N
1,68355089,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,small_business,Business,577xx,SD,16.06,1.0,Dec-1999,715.0,719.0,4.0,22.0,0.0,21470.0,19.2,38.0,w,0.0,0.0,25679.660000,25679.66,24700.0,979.66,0.0,0.0,0.0,Jun-2016,926.35,Mar-2019,699.0,695.0,0.0,1.0,Individual,0.0,0.0,204396.0,111800.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,N,Cash,N
2,68341763,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,home_improvement,NaN,605xx,IL,10.78,0.0,Aug-2000,695.0,699.0,0.0,6.0,0.0,7869.0,56.2,18.0,w,0.0,0.0,22705.924294,22705.92,20000.0,2705.92,0.0,0.0,0.0,Jun-2017,15813.30,Mar-2019,704.0,700.0,0.0,1.0,Joint App,0.0,0.0,189699.0,14000.0,6.0,31617.0,2737.0,55.9,0.0,0.0,125.0,184.0,14.0,14.0,5.0,101.0,0.0,2.0,3.0,2.0,4.0,6.0,4.0,7.0,3.0,6.0,0.0,0.0,0.0,0.0,100.0,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,N,Cash,N
4,68476807,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,MORTGAGE,104433.0,Source Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,major_purchase,Major purchase,174xx,PA,25.37,1.0,Jun-1998,695.0,699.0,3.0,12.0,0.0,21929.0,64.5,35.0,w,0.0,0.0,11740.500000,11740.50,10400.0,1340.50,0.0,0.0,0.0,Jul-2016,10128.96,Mar-2018,704.0,700.0,0.0,1.0,Individual,0.0,0.0,331730.0,34000.0,10.0,27644.0,4567.0,77.5,0.0,0.0,128.0,210.0,4.0,4.0,6.0,4.0,0.0,4.0,6.0,5.0,9.0,10.0,7.0,19.0,6.0,12.0,0.0,0.0,0.0,4.0,96.6,60.0,0.0,0.0,439570.0,95768.0,20300.0,88097.0,N,Cash,N
5,68426831,11950.0,11950.0,11950.0,36 months,13.44,405.18,C,C3,Veterinary Tecnician,4 years,RENT,34000.0,Source Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,debt_consolidation,Debt consolidation,300xx,GA,10.20,0.0,Oct-1987,690.0,694.0,0.0,5.0,0.0,8822.0,68.4,6.0,w,0.0,0.0,13708.948530,13708.95,11950.0,1758.95,0.0,0.0,0.0,May-2017,7653.56,May-2017,759.0,755.0,0.0,1.0,Individual,0.0,0.0,12798.0,12900.0,0.0,2560.0,844.0,91.0,0.0,0.0,338.0,54.0,32.0,32.0,0.0,36.0,0.0,2.0,3.0,2.0,2.0,2.0,4.0,4.0,3.0,5.0,0.0,0.0,0.0,0.0,100.0,100.0,0.0,0.0,16900.0,12798.0,9400.0,4000.0,N,Cash,N

In [101]:
df_copy.dtypes

id                             object
loan_amnt                     float64
funded_amnt                   float64
funded_amnt_inv               float64
term                           object
int_rate                      float64
installment                   float64
grade                          object
sub_grade                      object
emp_title                      object
emp_length                     object
home_ownership                 object
annual_inc                    float64
verification_status            object
issue_d                        object
loan_status                    object
pymnt_plan                     object
url                            object
purpose                        object
title                          object
zip_code                       object
addr_state                     object
dti                           float64
delinq_2yrs                   float64
earliest_cr_line               object
fico_range_low                float64
fico_range_high               float64
inq_last_6mths                float64
open_acc                      float64
pub_rec                       float64
revol_bal                     float64
revol_util                    float64
total_acc                     float64
initial_list_status            object
out_prncp                     float64
out_prncp_inv                 float64
total_pymnt                   float64
total_pymnt_inv               float64
total_rec_prncp               float64
total_rec_int                 float64
total_rec_late_fee            float64
recoveries                    float64
collection_recovery_fee       float64
last_pymnt_d                   object
last_pymnt_amnt               float64
last_credit_pull_d             object
last_fico_range_high          float64
last_fico_range_low           float64
collections_12_mths_ex_med    float64
policy_code                   float64
application_type               object
acc_now_delinq                float64
tot_coll_amt                  float64
tot_cur_bal                   float64
total_rev_hi_lim              float64
acc_open_past_24mths          float64
avg_cur_bal                   float64
bc_open_to_buy                float64
bc_util                       float64
chargeoff_within_12_mths      float64
delinq_amnt                   float64
mo_sin_old_il_acct            float64
mo_sin_old_rev_tl_op          float64
mo_sin_rcnt_rev_tl_op         float64
mo_sin_rcnt_tl                float64
mort_acc                      float64
mths_since_recent_bc          float64
num_accts_ever_120_pd         float64
num_actv_bc_tl                float64
num_actv_rev_tl               float64
num_bc_sats                   float64
num_bc_tl                     float64
num_il_tl                     float64
num_op_rev_tl                 float64
num_rev_accts                 float64
num_rev_tl_bal_gt_0           float64
num_sats                      float64
num_tl_120dpd_2m              float64
num_tl_30dpd                  float64
num_tl_90g_dpd_24m            float64
num_tl_op_past_12m            float64
pct_tl_nvr_dlq                float64
percent_bc_gt_75              float64
pub_rec_bankruptcies          float64
tax_liens                     float64
tot_hi_cred_lim               float64
total_bal_ex_mort             float64
total_bc_limit                float64
total_il_high_credit_limit    float64
hardship_flag                  object
disbursement_method            object
debt_settlement_flag           object
dtype: object

In [103]:
df_copy.select_dtypes('object').columns

Index(['id', 'term', 'grade', 'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'verification_status', 'issue_d', 'loan_status', 'pymnt_plan', 'url', 'purpose', 'title', 'zip_code', 'addr_state', 'earliest_cr_line', 'initial_list_status', 'last_pymnt_d', 'last_credit_pull_d', 'application_type', 'hardship_flag', 'disbursement_method', 'debt_settlement_flag'], dtype='object')

In [104]:
df_copy['term'].value_counts()

 36 months    1023181
 60 months     324878
Name: term, dtype: int64

In [111]:
df_copy['term'] = df_copy['term'].replace([' 36 months',' 60 months'],[36,60])

In [112]:
df_copy['term'].value_counts()

36    1023181
60     324878
Name: term, dtype: int64

In [113]:
df_copy['grade'].value_counts()

B    393095
C    382315
A    235188
D    201644
E     94186
F     32305
G      9326
Name: grade, dtype: int64

In [114]:
df_copy['grade'].unique()

array(['C', 'B', 'F', 'A', 'E', 'D', 'G'], dtype=object)

In [115]:
list(range(7))

[0, 1, 2, 3, 4, 5, 6]

In [116]:
df_copy['grade'] = df_copy['grade'].replace(['C', 'B', 'F', 'A', 'E', 'D', 'G'],[0,1,2,3,4,5,6])

In [117]:
df_copy['grade'].value_counts()

1    393095
0    382315
3    235188
5    201644
4     94186
2     32305
6      9326
Name: grade, dtype: int64

In [119]:
df_copy['emp_title'].value_counts()

Teacher                            21268
Manager                            19470
Owner                              10302
Registered Nurse                    8774
RN                                  8522
                                   ...
Sr. Facilities Mgr                     1
Licensed Refrigeration Engineer        1
Sr. Financial Analyst - FP&A           1
Elegibility Tech                       1
Exec Dir Internal Audit                1
Name: emp_title, Length: 379858, dtype: int64

In [121]:
df_copy['emp_length'].value_counts()

10+ years    442669
2 years      122092
< 1 year     108533
3 years      107863
1 year        88842
5 years       84326
4 years       80761
6 years       62877
8 years       60808
7 years       59724
9 years       51019
Name: emp_length, dtype: int64