In [1]:
import pandas as pd
import numpy as np
pd.options.display.max_rows = 100

In [2]:
data = {
    'Name': ['JAMES', 'JAMES', 'JAMES', 'JAMES', 'JAMES', 'JAMES', 'JAMES', 'JAMES', 'JAMES', 'JAMES', 'JAMES', 'JAMES', 'JAMES', 'JAMES', 'JAMES', 'JOHN', 'JOHN', 'JOHN', 'JOHN', 'JOHN', 'JOHN', 'JOHN', 'JOHN', 'JOHN', 'JOHN', 'JOHN', 'JOHN', 'JOHN', 'JOHN', 'JOHN', 'JOHN', 'JOHN', 'GWEN', 'GWEN', 'GWEN', 'GWEN', 'GWEN', 'GWEN', 'GWEN', 'GWEN', 'GWEN', 'GWEN', 'GWEN', 'LESSY', 'LESSY', 'AVINASH', 'AVINASH', 'AVINASH', 'AVINASH'], 
    'Col A': [2.222222, 2.222222, 2.222222, 2.222222, 2.222222, 2.222222, 2.222222, 2.222222, 2.222222, 3.333333, 3.333333, 3.333333, 3.333333, 3.333333, 3.333333, 1.867, 1.867, 1.867, 1.867, 1.867, 1.867, 1.867, 1.867, 1.867, 2.88, 2.88, 3.04, 2.88, 2.88, 2.88, 2.88, 2.88, 5.76, 3.387, 2.373, 1.867, 1.867, 1.867, 3.733, 1.867, 5.76, 5.76, 5.76, 8, 8, 5, 4, 4, 8],
    'Col B': [1.777778, 1.777778, 1.777778, 1.777778, 1.777778, 1.777778, 1.777778, 1.777778, 1.777778, 2.666667, 2.666667, 2.666667, 2.666667, 2.666667, 2.666667, 2.133, 2.133, 2.133, 2.133, 2.133, 2.133, 2.133, 2.133, 2.133, 3.12, 3.12, 2.96, 3.12, 3.12, 3.12, 3.12, 3.12, 6.24, 3.613, 2.627, 2.133, 2.133, 2.133, 4.267, 2.133, 6.24, 6.24, 6.24, 5, 4, 0, 0, 0, 4]
}

df = pd.DataFrame(data)

df['Rounded Col A'] = df['Col A'].apply(round, ndigits=2)
df['Rounded Col B'] = df['Col B'].apply(round, ndigits=2)

df['Sum A and B Rounded'] = df['Rounded Col A'] + df['Rounded Col B']

df

,Name,Col A,Col B,Rounded Col A,Rounded Col B,Sum A and B Rounded
0,JAMES,2.222222,1.777778,2.22,1.78,4.0
1,JAMES,2.222222,1.777778,2.22,1.78,4.0
2,JAMES,2.222222,1.777778,2.22,1.78,4.0
3,JAMES,2.222222,1.777778,2.22,1.78,4.0
4,JAMES,2.222222,1.777778,2.22,1.78,4.0
5,JAMES,2.222222,1.777778,2.22,1.78,4.0
6,JAMES,2.222222,1.777778,2.22,1.78,4.0
7,JAMES,2.222222,1.777778,2.22,1.78,4.0
8,JAMES,2.222222,1.777778,2.22,1.78,4.0
9,JAMES,3.333333,2.666667,3.33,2.67,6.0
10,JAMES,3.333333,2.666667,3.33,2.67,6.0
11,JAMES,3.333333,2.666667,3.33,2.67,6.0
12,JAMES,3.333333,2.666667,3.33,2.67,6.0
13,JAMES,3.333333,2.666667,3.33,2.67,6.0
14,JAMES,3.333333,2.666667,3.33,2.67,6.0
15,JOHN,1.867000,2.133000,1.87,2.13,4.0
16,JOHN,1.867000,2.133000,1.87,2.13,4.0
17,JOHN,1.867000,2.133000,1.87,2.13,4.0
18,JOHN,1.867000,2.133000,1.87,2.13,4.0
19,JOHN,1.867000,2.133000,1.87,2.13,4.0
20,JOHN,1.867000,2.133000,1.87,2.13,4.0
21,JOHN,1.867000,2.133000,1.87,2.13,4.0
22,JOHN,1.867000,2.133000,1.87,2.13,4.0
23,JOHN,1.867000,2.133000,1.87,2.13,4.0
24,JOHN,2.880000,3.120000,2.88,3.12,6.0
25,JOHN,2.880000,3.120000,2.88,3.12,6.0
26,JOHN,3.040000,2.960000,3.04,2.96,6.0
27,JOHN,2.880000,3.120000,2.88,3.12,6.0
28,JOHN,2.880000,3.120000,2.88,3.12,6.0
29,JOHN,2.880000,3.120000,2.88,3.12,6.0
30,JOHN,2.880000,3.120000,2.88,3.12,6.0
31,JOHN,2.880000,3.120000,2.88,3.12,6.0
32,GWEN,5.760000,6.240000,5.76,6.24,12.0
33,GWEN,3.387000,3.613000,3.39,3.61,7.0
34,GWEN,2.373000,2.627000,2.37,2.63,5.0
35,GWEN,1.867000,2.133000,1.87,2.13,4.0
36,GWEN,1.867000,2.133000,1.87,2.13,4.0
37,GWEN,1.867000,2.133000,1.87,2.13,4.0
38,GWEN,3.733000,4.267000,3.73,4.27,8.0
39,GWEN,1.867000,2.133000,1.87,2.13,4.0
40,GWEN,5.760000,6.240000,5.76,6.24,12.0
41,GWEN,5.760000,6.240000,5.76,6.24,12.0
42,GWEN,5.760000,6.240000,5.76,6.24,12.0
43,LESSY,8.000000,5.000000,8.00,5.00,13.0
44,LESSY,8.000000,4.000000,8.00,4.00,12.0
45,AVINASH,5.000000,0.000000,5.00,0.00,5.0
46,AVINASH,4.000000,0.000000,4.00,0.00,4.0
47,AVINASH,4.000000,0.000000,4.00,0.00,4.0
48,AVINASH,8.000000,4.000000,8.00,4.00,12.0

In [3]:
df['Total Meta Weight'] = df.groupby(['Name'])['Col A'].transform('sum').apply(round, 2)

df.loc[(df['Total Meta Weight'] > 39.8),'Total Meta Weight'] = 40
df.loc[(df['Total Meta Weight'] <= 39.8),'Total Meta Weight'] = df['Total Meta Weight']

### NEED TO FIND A CONDITIONAL ON THE LAMDA SO THAT THIS USES SUM TO CALCULATE TOTAL
# df['Ouput Round A'] = (df['Rounded Col A']
#  .round(2)
#  .groupby(df['Name'])
#  ### This commented out code works but it is hard coded at 40
# #  .transform(lambda s: pd.Series({s.index[-1]: (40-s.iloc[:-1].sum())})
#  ### This is what I tried using the 'Total Meta Weight' column as the variable, 
#  #but as you can see on the output it uses the whole series to use the corresponding row 'total meta weight'
#  .transform(lambda s: pd.Series({s.index[-1]: (df['Total Meta Weight']-s.iloc[:-1].sum())})
#  .combine_first(s))
# )

In [4]:
df

,Name,Col A,Col B,Rounded Col A,Rounded Col B,Sum A and B Rounded,Total Meta Weight
0,JAMES,2.222222,1.777778,2.22,1.78,4.0,40
1,JAMES,2.222222,1.777778,2.22,1.78,4.0,40
2,JAMES,2.222222,1.777778,2.22,1.78,4.0,40
3,JAMES,2.222222,1.777778,2.22,1.78,4.0,40
4,JAMES,2.222222,1.777778,2.22,1.78,4.0,40
5,JAMES,2.222222,1.777778,2.22,1.78,4.0,40
6,JAMES,2.222222,1.777778,2.22,1.78,4.0,40
7,JAMES,2.222222,1.777778,2.22,1.78,4.0,40
8,JAMES,2.222222,1.777778,2.22,1.78,4.0,40
9,JAMES,3.333333,2.666667,3.33,2.67,6.0,40
10,JAMES,3.333333,2.666667,3.33,2.67,6.0,40
11,JAMES,3.333333,2.666667,3.33,2.67,6.0,40
12,JAMES,3.333333,2.666667,3.33,2.67,6.0,40
13,JAMES,3.333333,2.666667,3.33,2.67,6.0,40
14,JAMES,3.333333,2.666667,3.33,2.67,6.0,40
15,JOHN,1.867000,2.133000,1.87,2.13,4.0,40
16,JOHN,1.867000,2.133000,1.87,2.13,4.0,40
17,JOHN,1.867000,2.133000,1.87,2.13,4.0,40
18,JOHN,1.867000,2.133000,1.87,2.13,4.0,40
19,JOHN,1.867000,2.133000,1.87,2.13,4.0,40
20,JOHN,1.867000,2.133000,1.87,2.13,4.0,40
21,JOHN,1.867000,2.133000,1.87,2.13,4.0,40
22,JOHN,1.867000,2.133000,1.87,2.13,4.0,40
23,JOHN,1.867000,2.133000,1.87,2.13,4.0,40
24,JOHN,2.880000,3.120000,2.88,3.12,6.0,40
25,JOHN,2.880000,3.120000,2.88,3.12,6.0,40
26,JOHN,3.040000,2.960000,3.04,2.96,6.0,40
27,JOHN,2.880000,3.120000,2.88,3.12,6.0,40
28,JOHN,2.880000,3.120000,2.88,3.12,6.0,40
29,JOHN,2.880000,3.120000,2.88,3.12,6.0,40
30,JOHN,2.880000,3.120000,2.88,3.12,6.0,40
31,JOHN,2.880000,3.120000,2.88,3.12,6.0,40
32,GWEN,5.760000,6.240000,5.76,6.24,12.0,40
33,GWEN,3.387000,3.613000,3.39,3.61,7.0,40
34,GWEN,2.373000,2.627000,2.37,2.63,5.0,40
35,GWEN,1.867000,2.133000,1.87,2.13,4.0,40
36,GWEN,1.867000,2.133000,1.87,2.13,4.0,40
37,GWEN,1.867000,2.133000,1.87,2.13,4.0,40
38,GWEN,3.733000,4.267000,3.73,4.27,8.0,40
39,GWEN,1.867000,2.133000,1.87,2.13,4.0,40
40,GWEN,5.760000,6.240000,5.76,6.24,12.0,40
41,GWEN,5.760000,6.240000,5.76,6.24,12.0,40
42,GWEN,5.760000,6.240000,5.76,6.24,12.0,40
43,LESSY,8.000000,5.000000,8.00,5.00,13.0,16
44,LESSY,8.000000,4.000000,8.00,4.00,12.0,16
45,AVINASH,5.000000,0.000000,5.00,0.00,5.0,21
46,AVINASH,4.000000,0.000000,4.00,0.00,4.0,21
47,AVINASH,4.000000,0.000000,4.00,0.00,4.0,21
48,AVINASH,8.000000,4.000000,8.00,4.00,12.0,21

In [5]:
# In [99]: df.groupby(['c', 'd']).transform(lambda x: pd.Series(np.sum(x['a']+x['b'])))

In [6]:
# df['Ouput Round A'] = (df[['Total Meta Weight','Rounded Col A']]
#  .round(2)
#  .groupby(df['Name'])
#  ### This commented out code works but it is hard coded at 40
# #  .transform(lambda s: pd.Series({s.index[-1]: (40-s.iloc[:-1].sum())})
#  ### This is what I tried using the 'Total Meta Weight' column as the variable, 
#  #but as you can see on the output it uses the whole series to use the corresponding row 'total meta weight'
#  .transform(lambda s: s['Rounded Col A'].sum())
#                       )

In [7]:
df

,Name,Col A,Col B,Rounded Col A,Rounded Col B,Sum A and B Rounded,Total Meta Weight
0,JAMES,2.222222,1.777778,2.22,1.78,4.0,40
1,JAMES,2.222222,1.777778,2.22,1.78,4.0,40
2,JAMES,2.222222,1.777778,2.22,1.78,4.0,40
3,JAMES,2.222222,1.777778,2.22,1.78,4.0,40
4,JAMES,2.222222,1.777778,2.22,1.78,4.0,40
5,JAMES,2.222222,1.777778,2.22,1.78,4.0,40
6,JAMES,2.222222,1.777778,2.22,1.78,4.0,40
7,JAMES,2.222222,1.777778,2.22,1.78,4.0,40
8,JAMES,2.222222,1.777778,2.22,1.78,4.0,40
9,JAMES,3.333333,2.666667,3.33,2.67,6.0,40
10,JAMES,3.333333,2.666667,3.33,2.67,6.0,40
11,JAMES,3.333333,2.666667,3.33,2.67,6.0,40
12,JAMES,3.333333,2.666667,3.33,2.67,6.0,40
13,JAMES,3.333333,2.666667,3.33,2.67,6.0,40
14,JAMES,3.333333,2.666667,3.33,2.67,6.0,40
15,JOHN,1.867000,2.133000,1.87,2.13,4.0,40
16,JOHN,1.867000,2.133000,1.87,2.13,4.0,40
17,JOHN,1.867000,2.133000,1.87,2.13,4.0,40
18,JOHN,1.867000,2.133000,1.87,2.13,4.0,40
19,JOHN,1.867000,2.133000,1.87,2.13,4.0,40
20,JOHN,1.867000,2.133000,1.87,2.13,4.0,40
21,JOHN,1.867000,2.133000,1.87,2.13,4.0,40
22,JOHN,1.867000,2.133000,1.87,2.13,4.0,40
23,JOHN,1.867000,2.133000,1.87,2.13,4.0,40
24,JOHN,2.880000,3.120000,2.88,3.12,6.0,40
25,JOHN,2.880000,3.120000,2.88,3.12,6.0,40
26,JOHN,3.040000,2.960000,3.04,2.96,6.0,40
27,JOHN,2.880000,3.120000,2.88,3.12,6.0,40
28,JOHN,2.880000,3.120000,2.88,3.12,6.0,40
29,JOHN,2.880000,3.120000,2.88,3.12,6.0,40
30,JOHN,2.880000,3.120000,2.88,3.12,6.0,40
31,JOHN,2.880000,3.120000,2.88,3.12,6.0,40
32,GWEN,5.760000,6.240000,5.76,6.24,12.0,40
33,GWEN,3.387000,3.613000,3.39,3.61,7.0,40
34,GWEN,2.373000,2.627000,2.37,2.63,5.0,40
35,GWEN,1.867000,2.133000,1.87,2.13,4.0,40
36,GWEN,1.867000,2.133000,1.87,2.13,4.0,40
37,GWEN,1.867000,2.133000,1.87,2.13,4.0,40
38,GWEN,3.733000,4.267000,3.73,4.27,8.0,40
39,GWEN,1.867000,2.133000,1.87,2.13,4.0,40
40,GWEN,5.760000,6.240000,5.76,6.24,12.0,40
41,GWEN,5.760000,6.240000,5.76,6.24,12.0,40
42,GWEN,5.760000,6.240000,5.76,6.24,12.0,40
43,LESSY,8.000000,5.000000,8.00,5.00,13.0,16
44,LESSY,8.000000,4.000000,8.00,4.00,12.0,16
45,AVINASH,5.000000,0.000000,5.00,0.00,5.0,21
46,AVINASH,4.000000,0.000000,4.00,0.00,4.0,21
47,AVINASH,4.000000,0.000000,4.00,0.00,4.0,21
48,AVINASH,8.000000,4.000000,8.00,4.00,12.0,21

In [8]:
y = df.loc[df.groupby('Name')['Total Meta Weight'].tail(1).index, 'Total Meta Weight']

x = df.groupby('Name').apply(lambda x: set(x['Total Meta Weight']).pop() - x['Rounded Col A'].sum())

x = dict(x)

In [11]:
df['Ouput Round A'] = df['Rounded Col A'].round(2).groupby(df['Name']).apply(lambda x:x)

In [12]:
val = []
for indx,row in df.iterrows():
    if indx in y.index:
        val.append(row['Ouput Round A'] + x[row['Name']])
    else:
        val.append(row['Ouput Round A'])

In [13]:
df['Ouput Round A'] = val

In [14]:
df.to_csv('see_new.csv')

In [21]:
df.groupby('Name').apply(lambda x: set(x['Total Meta Weight']).pop()-sum(x['Rounded Col A']))

Name
AVINASH    0.00
GWEN      -0.01
JAMES      0.04
JOHN      -0.03
LESSY      0.00
dtype: float64