In [1]:
import pandas as pd

In [7]:
df = pd.read_csv(r'C:\Users\avitr\Downloads\crime\crime.csv',encoding='ANSI')

In [8]:
df

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,I182054381,3301,Verbal Disputes,VERBAL DISPUTE,B3,428,NaN,2018-07-10 20:57:00,2018,7,Tuesday,20,Part Three,BLUE HILL AVE,42.282829,-71.091825,"(42.28282878, -71.09182490)"
1,I182054379,3114,Investigate Property,INVESTIGATE PROPERTY,E18,481,NaN,2018-07-10 21:16:00,2018,7,Tuesday,21,Part Three,ROCKDALE ST,42.266525,-71.098553,"(42.26652466, -71.09855320)"
2,I182054378,619,Larceny,LARCENY ALL OTHERS,B2,182,NaN,2018-07-10 21:27:00,2018,7,Tuesday,21,Part One,BATCHELDER ST,42.322496,-71.069092,"(42.32249601, -71.06909180)"
3,I182054376,617,Larceny,LARCENY THEFT FROM BUILDING,E5,714,NaN,2018-07-10 18:39:00,2018,7,Tuesday,18,Part One,VOGEL ST,42.262539,-71.165069,"(42.26253888, -71.16506913)"
4,I182054374,3410,Towed,TOWED MOTOR VEHICLE,C6,211,NaN,2018-07-10 20:11:00,2018,7,Tuesday,20,Part Three,W THIRD ST,42.338964,-71.048964,"(42.33896439, -71.04896420)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303366,I050310906-00,3125,Warrant Arrests,WARRANT ARREST,D4,285,NaN,2016-06-05 17:25:00,2016,6,Sunday,17,Part Three,COVENTRY ST,42.336951,-71.085748,"(42.33695098, -71.08574813)"
303367,I030217815-08,111,Homicide,"MURDER, NON-NEGLIGIENT MANSLAUGHTER",E18,520,NaN,2015-07-09 13:38:00,2015,7,Thursday,13,Part One,RIVER ST,42.255926,-71.123172,"(42.25592648, -71.12317207)"
303368,I030217815-08,3125,Warrant Arrests,WARRANT ARREST,E18,520,NaN,2015-07-09 13:38:00,2015,7,Thursday,13,Part Three,RIVER ST,42.255926,-71.123172,"(42.25592648, -71.12317207)"
303369,I010370257-00,3125,Warrant Arrests,WARRANT ARREST,E13,569,NaN,2016-05-31 19:35:00,2016,5,Tuesday,19,Part Three,NEW WASHINGTON ST,42.302333,-71.111565,"(42.30233307, -71.11156487)"
303370,142052550,3125,Warrant Arrests,WARRANT ARREST,D4,903,NaN,2015-06-22 00:12:00,2015,6,Monday,0,Part Three,WASHINGTON ST,42.333839,-71.080290,"(42.33383935, -71.08029038)"

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
StandardScaler

sklearn.preprocessing._data.StandardScaler