Graphically summarize the top 10 unigram and bigrams of the tf-idf of the text of the Tweet_texts.

Visualize the top 10 term frequency of the tokens associated with positive tweets using scattertext.

Visualize the top 10 positive scores of the tokens associated with positive tweets using scattertext.

Convert the column of the Tweet_texts to a matrix of token counts using CountVectorizer and unigrams and bigrams.

Perform the tf-idf analysis on the column of the Tweet_texts using Tfidfvectorizer.

Find the cosine similarity in Tweet_texts between the 200th and 20,000th tweets.
Find the corpus vector equal to the average of all the document vectors, where each document corresponds to a tweet or a row in this dataset.
For steps 15 to 20, we want to forecast Sentiment using Tweet_texts.

Build the first model based on the training dataset using the random forests and pipeline.

Check the first model on the test dataset. Is it a good model based on the selected evaluation metrics? Please justify your answer.

Create the second model using random forest, pipeline, grid search CV for the hyperparameters for the estimators. (Please see all the potential parameters at Scikit Learn's TfidVectorizerLinks to an external site. and random forestsLinks to an external site..)

Tune the second model and perform model diagnostics on the test dataset. Is it a good model? Please justify your answer.

Build the third model using pipeline, grid search CV, hyperparameter for the following classifiers:
Logistic Regression
Support Vector Machine
Random Forest

Tune the third model and perform model diagnostics on the test dataset. Is it a good model? Please justify your answer.
For the Q21 to Q25, please only works on the training dataset

21. Generate the first topic model by setting five topics using LDA method and CountVectorizer.

22. Plot the top 15 words for each topic for the model above.

23. Generate the second topic model by setting five topics using LDA method and TfidfVectorizer.

24. Plot the top 15 words for each topic for the second model above.

25. Visualize the second topic model using the dimension reduction method. (You may choose the method you like)

In [ ]:
Visualize the top 10 positive scores of the tokens associated with positive tweets using scattertext.
Convert the column of the Tweet_texts to a matrix of token counts using CountVectorizer and unigrams and bigrams.
Perform the tf-idf analysis on the column of the Tweet_texts using Tfidfvectorizer.
Find the cosine similarity in Tweet_texts between the 200th and 20,000th tweets.
Find the corpus vector equal to the average of all the document vectors, where each document corresponds to a tweet or a row in this dataset.
For steps 15 to 20, we want to forecast Sentiment using Tweet_texts.

Build the first model based on the training dataset using the random forests and pipeline.
Check the first model on the test dataset. Is it a good model based on the selected evaluation metrics? Please justify your answer.
Create the second model using random forest, pipeline, grid search CV for the hyperparameters for the estimators. (Please see all the potential parameters at Scikit Learn's TfidVectorizerLinks to an external site. and random forestsLinks to an external site..)
Tune the second model and perform model diagnostics on the test dataset. Is it a good model? Please justify your answer.
Build the third model using pipeline, grid search CV, hyperparameter for the following classifiers:
Logistic Regression
Support Vector Machine
Random Forest
Tune the third model and perform model diagnostics on the test dataset. Is it a good model? Please justify your answer.

# CODE

In [9]:
import pandas as pd
try:
    import scattertext as st
except:
    !pip install scattertext

In [5]:
df_train = pd.read_csv("D:\OneDrive - NITT\Custom_Download\Corona_NLP_train.csv",encoding="latin-1")
df_test = pd.read_csv("D:\OneDrive - NITT\Custom_Download\Corona_NLP_test.csv",encoding="latin-1")

In [6]:
df_train

,UserName,ScreenName,Location,TweetAt,OriginalTweet,Sentiment
0,3799,48751,London,16-03-2020,@MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...,Neutral
1,3800,48752,UK,16-03-2020,advice Talk to your neighbours family to excha...,Positive
2,3801,48753,Vagabonds,16-03-2020,Coronavirus Australia: Woolworths to give elde...,Positive
3,3802,48754,NaN,16-03-2020,My food stock is not the only one which is emp...,Positive
4,3803,48755,NaN,16-03-2020,"Me, ready to go at supermarket during the #COV...",Extremely Negative
...,...,...,...,...,...,...
41152,44951,89903,"Wellington City, New Zealand",14-04-2020,Airline pilots offering to stock supermarket s...,Neutral
41153,44952,89904,NaN,14-04-2020,Response to complaint not provided citing COVI...,Extremely Negative
41154,44953,89905,NaN,14-04-2020,You know itÂs getting tough when @KameronWild...,Positive
41155,44954,89906,NaN,14-04-2020,Is it wrong that the smell of hand sanitizer i...,Neutral
41156,44955,89907,i love you so much || he/him,14-04-2020,@TartiiCat Well new/used Rift S are going for ...,Negative

In [7]:
df_test

,UserName,ScreenName,Location,TweetAt,OriginalTweet,Sentiment
0,1,44953,NYC,02-03-2020,TRENDING: New Yorkers encounter empty supermar...,Extremely Negative
1,2,44954,"Seattle, WA",02-03-2020,When I couldn't find hand sanitizer at Fred Me...,Positive
2,3,44955,NaN,02-03-2020,Find out how you can protect yourself and love...,Extremely Positive
3,4,44956,Chicagoland,02-03-2020,#Panic buying hits #NewYork City as anxious sh...,Negative
4,5,44957,"Melbourne, Victoria",03-03-2020,#toiletpaper #dunnypaper #coronavirus #coronav...,Neutral
...,...,...,...,...,...,...
3793,3794,48746,Israel ??,16-03-2020,Meanwhile In A Supermarket in Israel -- People...,Positive
3794,3795,48747,"Farmington, NM",16-03-2020,Did you panic buy a lot of non-perishable item...,Negative
3795,3796,48748,"Haverford, PA",16-03-2020,Asst Prof of Economics @cconces was on @NBCPhi...,Neutral
3796,3797,48749,NaN,16-03-2020,Gov need to do somethings instead of biar je r...,Extremely Negative
3797,3798,48750,"Arlington, Virginia",16-03-2020,I and @ForestandPaper members are committed to...,Extremely Positive