In [2]:
import pandas as pd
import requests
import csv

url = 'http://bexar.trueautomation.com/clientdb/Property.aspx?cid=110&prop_id=525041'
page = requests.get(url)

df = pd.read_html(url, match='Property ID')

# for i in df:
#     i.to_csv("bexar.csv", index = False)

In [6]:
data = df[0]

In [13]:
data.iloc[:,0].to_list()

['Account',
 'Property ID:',
 'Geographic ID:',
 'Type:',
 'Property Use Code:',
 'Property Use Description:',
 'Protest',
 'Protest Status:',
 'Informal Date:',
 'Formal Date:',
 'Location',
 'Address:',
 'Neighborhood:',
 'Neighborhood CD:',
 'Owner',
 'Name:',
 'Mailing Address:',
 nan]

In [10]:
data.head()

                    0               1                   2                    3
0             Account         Account             Account              Account
1        Property ID:          525041  Legal Description:  NCB 13416 BLK LOT 6
2      Geographic ID:  13416-000-0060             Zoning:                    D
3               Type:            Real         Agent Code:                60585
4  Property Use Code:             098                 NaN                  NaN

In [15]:
columns = data.iloc[:,0].to_list() + data.iloc[:,2].to_list()

In [17]:
len(columns)

36

In [18]:
data

,0,1,2,3
0,Account,Account,Account,Account
1,Property ID:,525041,Legal Description:,NCB 13416 BLK LOT 6
2,Geographic ID:,13416-000-0060,Zoning:,D
3,Type:,Real,Agent Code:,60585
4,Property Use Code:,098,NaN,NaN
5,Property Use Description:,TRANSITIONAL USE,NaN,NaN
6,Protest,Protest,Protest,Protest
7,Protest Status:,NaN,NaN,NaN
8,Informal Date:,NaN,NaN,NaN
9,Formal Date:,NaN,NaN,NaN
10,Location,Location,Location,Location
11,Address:,"215 S SAN SABA SAN ANTONIO, TX 78207",Mapsco:,616D5
12,Neighborhood:,NBHD code10030,Map ID:,NaN
13,Neighborhood CD:,10030,E-File Eligible,E-File Eligible
14,Owner,Owner,Owner,Owner
15,Name:,SAN SABA OPPORTUNITY FUND LP,Owner ID:,3193041
16,Mailing Address:,"215 S SAN SABA #120 SAN ANTONIO, TX 78207",% Ownership:,100.0000000000%
17,NaN,NaN,Exemptions:,NaN

In [21]:
row_value = data.iloc[:,1].to_list() + data.iloc[:,3].to_list()