In [1]:
import pandas as pd

In [3]:
df = pd.read_excel('low_correlation_all_strategies_2ylookback_2021011.xlsx')

In [4]:
df

,yyyymmm,initial_nav,bgn_nav,end_nav,idx_return,num_of_funds,avg_ret,metric,ranking_by
0,2005001,50000.000000,50000.000000,50692.287753,1.301242,50,1.301242,correlation,50_low_correlation_ex_low_vol_0
1,2005002,50000.000000,50692.287753,51437.387164,1.386514,50,1.366994,correlation,50_low_correlation_ex_low_vol_0
2,2005003,50000.000000,51437.387164,51532.388127,0.101359,50,0.092069,correlation,50_low_correlation_ex_low_vol_0
3,2005004,49964.224418,51532.388127,51535.969071,-0.076384,50,-0.102986,correlation,50_low_correlation_ex_low_vol_0
4,2005005,49988.671339,51535.969071,51462.466973,-0.225956,50,-0.186211,correlation,50_low_correlation_ex_low_vol_0
...,...,...,...,...,...,...,...,...,...
4867,2021007,380550.171871,425120.601982,422741.170068,-0.643041,198,-0.651068,correlation,300_low_correlation_ex_low_vol_150
4868,2021008,382520.416922,420666.623998,424249.343789,0.768343,197,0.637655,correlation,300_low_correlation_ex_low_vol_150
4869,2021009,378822.273359,417927.450303,416735.320062,-0.368581,194,-0.376427,correlation,300_low_correlation_ex_low_vol_150
4870,2021010,321129.868770,354784.892139,363494.542440,2.371577,165,2.243324,correlation,300_low_correlation_ex_low_vol_150
4871,2021011,267993.745322,302960.356449,294019.269550,-3.034573,137,-3.000444,correlation,300_low_correlation_ex_low_vol_150