In [81]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [82]:
df = pd.read_excel('Product list as of 31.12.2021.xlsx')

In [83]:
df.columns=['Product / Underlying','Fee','ISIN','WKN','Currency',
'SIX Swiss Exchange','Deutsche Börse Xetra','Euronext Amsterdam','Euronext Paris','Wiener Börse','Nasdaq Stockholm','BX Swiss','Börse Stuttgart','Börse Düsseldorf']

In [84]:
df = df.iloc[5:]

df.reset_index(drop=True,inplace=True)

df = df[~df['Product / Underlying'].isna()]
df = df[~(df['Product / Underlying']=='\xa0')]

df.reset_index(drop=True,inplace=True)

In [85]:
df

                       Product / Underlying     Fee          ISIN     WKN  Currency SIX Swiss Exchange Deutsche Börse Xetra Euronext Amsterdam Euronext Paris Wiener Börse Nasdaq Stockholm    BX Swiss Börse Stuttgart Börse Düsseldorf
0                     21Shares Algorand ETP   0.025  CH1146882316  A3GVVU       USD            ALGO SE                  NaN                NaN            NaN          NaN              NaN         NaN             NaN              NaN
1                    21Shares Avalanche ETP   0.025  CH1135202088  A3GVVT       CHF         AVAXCHF SE                  NaN                NaN            NaN          NaN              NaN         NaN             NaN              NaN
2                    21Shares Avalanche ETP   0.025  CH1135202088  A3GVVT       EUR         AVAXEUR SE                  NaN                NaN            NaN          NaN              NaN         NaN             NaN              NaN
3                    21Shares Avalanche ETP   0.025  CH1135202088  A3GVVT       USD            AVAX SE                  NaN                NaN            NaN          NaN              NaN         NaN             NaN              NaN
4                  21Shares Binance BNB ETP   0.025  CH0496454155  A22GRU       CHF                                                                                                     NaN     ABNB BW
5                  21Shares Binance BNB ETP   0.025  CH0496454155  A22GRU       EUR                                                                   BNBA FP                           NaN                                      21XJ GD
6                  21Shares Binance BNB ETP   0.025  CH0496454155  A22GRU       USD            ABNB SE                                 BNBA NA                                          NaN
7                 21Shares Bitcoin Cash ETP   0.025  CH0475552201  A2126N       CHF                                                                                                     NaN  ABCHCHF BW
8                 21Shares Bitcoin Cash ETP   0.025  CH0475552201  A2126N       EUR                                 ABCH GY                           ABCH FP                           NaN                     ABCH GS          ABCH GD
9                 21Shares Bitcoin Cash ETP   0.025  CH0475552201  A2126N       USD            ABCH SE                                 ABCH NA                                          NaN
10                     21Shares Bitcoin ETP  0.0149  CH0454664001  A2T64E       CHF         ABTCCHF SE                                                                                  NaN  ABTCCHF BW
11                     21Shares Bitcoin ETP  0.0149  CH0454664001  A2T64E       EUR         ABTCEUR SE              2BTC GY                           ABTC FP      ABTC AV              NaN                     2BTC GS          2BTC GD
12                     21Shares Bitcoin ETP  0.0149  CH0454664001  A2T64E       GBP         ABTCGBP SE                                                                                  NaN
13                     21Shares Bitcoin ETP  0.0149  CH0454664001  A2T64E       USD            ABTC SE                  NaN            ABTC NA                                          NaN
14                     21Shares Bitcoin ETP  0.0149  CH0454664001  A2T64E       SEK                NaN                  NaN                NaN            NaN          NaN          ABTC SS         NaN             NaN              NaN
15                     21Shares Cardano ETP   0.025  CH1102728750  A3GRTN       EUR                                 ADAA GY                                                             NaN                     ADAA GS          ADAA GD
16                     21Shares Cardano ETP   0.025  CH1102728750  A3GRTN       USD            AADA SE                                                                                  NaN
17                    21Shares Ethereum ETP  0.0149  CH0454664027  A2T68Z       CHF         AETHCHF SE                                                                                  NaN  AETHCHF BW
18                    21Shares Ethereum ETP  0.0149  CH0454664027  A2T68Z       EUR         AETHEUR SE              ETHA GY                           AETH FP      AETH AV              NaN                     ETHA GS          ETHA GD
19                    21Shares Ethereum ETP  0.0149  CH0454664027  A2T68Z       GBP         AETHGBP SE                                                                                  NaN
20                    21Shares Ethereum ETP  0.0149  CH0454664027  A2T68Z       USD            AETH SE                  NaN            AETH NA                                          NaN
21                    21Shares Ethereum ETP  0.0149  CH0454664027  A2T68Z       SEK                NaN                  NaN                NaN            NaN          NaN          AETH SS         NaN             NaN              NaN
22                    21Shares Polkadot ETP   0.025  CH0593331561  A3GPQM       EUR                                 ADOT GY                           ADOT FP                           NaN                     ADOT GS          ADOT GD
23                    21Shares Polkadot ETP   0.025  CH0593331561  A3GPQM       USD            ADOT SE                                 ADOT NA                                          NaN
24                     21Shares Polygon ETP   0.025  CH1129538448  A3GUQJ       CHF         POLYCHF SE                  NaN                NaN            NaN          NaN              NaN         NaN             NaN              NaN
25                     21Shares Polygon ETP   0.025  CH1129538448  A3GUQJ       EUR         POLYEUR SE                  NaN                NaN       MATIC FP          NaN              NaN         NaN             NaN              NaN
26                     21Shares Polygon ETP   0.025  CH1129538448  A3GUQJ       USD            POLY SE                                MATIC NA                                          NaN
27                  21Shares Ripple XRP ETP   0.025  CH0454664043  A2UBKC       CHF                                                                                                     NaN  AXRPCHF BW
28                  21Shares Ripple XRP ETP   0.025  CH0454664043  A2UBKC       EUR                                                                   AXRP FP                           NaN                     21XX GS          21XX GD
29                  21Shares Ripple XRP ETP   0.025  CH0454664043  A2UBKC       USD            AXRP SE                                 AXRP NA                                          NaN
30                  21Shares Solana SOL ETP   0.025  CH1114873776  A3GSS0       EUR                                 ASOL GY                           ASOL FP                           NaN                     ASOL GS          ASOL GD
31                  21Shares Solana SOL ETP   0.025  CH1114873776  A3GSS0       USD            ASOL SE                                 ASOL NA                                          NaN
32                     21Shares Stellar ETP   0.025  CH1109575535  A3GRTM       EUR                                 XLME GY                           AXLM FP                           NaN                     XLME GS          XLME GD
33                     21Shares Stellar ETP   0.025  CH1109575535  A3GRTM       USD            AXLM SE                                 AXLM NA                                          NaN
34                       21Shares Tezos ETP   0.025  CH0491507486  A22J1S       CHF                                                                                                     NaN  AXTZCHF BW
35                       21Shares Tezos ETP   0.025  CH0491507486  A22J1S       EUR                                 AXTZ GY                                                             NaN                     AXTZ GS          AXTZ GD
36                       21Shares Tezos ETP   0.025  CH0491507486  A22J1S       USD            AXTZ SE                                 AXTZ NA        AXTZ FP                           NaN
37                     Product / Underlying     Fee          ISIN     WKN  Currency             Ticker               Ticker             Ticker         Ticker       Ticker           Ticker      Ticker          Ticker           Ticker
38                             Multi Assets                                                                                                                                             NaN
39        21Shares Bitcoin Suisse Index ETP   0.025  CH0496484640  A22FMC       CHF            ABBA SE                                                                                  NaN
40        21Shares Bitcoin Suisse Index ETP   0.025  CH0496484640  A22FMC       EUR                                                                                                     NaN                     21XA GS          21XA GD
41         21Shares Bitwise Select 10 ETP *   0.025  CH0475986318  A2107P       EUR                                                                                                     NaN                     ZZUC GS          ZZUC GD
42         21Shares Bitwise Select 10 ETP *   0.025  CH0475986318  A2107P       USD            KEYS SE                                                                                  NaN
43            21Shares Crypto Basket 10 ETP   0.025  CH1135202179  A3GUMU       USD           HODLX SE                                                                                  NaN
44  21Shares Crypto Basket Equal Weight ETP   0.025  CH1135202161  A3GUMV       USD           HODLV SE                                                                                  NaN
45         21Shares Crypto Basket Index ETP   0.025  CH0445689208  A2TT3D       EUR         HODLEUR SE              21XH GY                                                             NaN                     21XH GS          21XH GD
46         21Shares Crypto Basket Index ETP   0.025  CH0445689208  A2TT3D       GBP         HODLGBP SE                                                                                  NaN
47         21Shares Crypto Basket Index ETP   0.025  CH0445689208  A2TT3D       USD            HODL SE                                                                                  NaN
48        21Shares Crypto Mid-Cap Index ETP   0.025  CH1130675676  A3GWD4       CHF         ALTSCHF SE                  NaN                NaN            NaN          NaN              NaN         NaN             NaN              NaN
49        21Shares Crypto Mid-Cap Index ETP   0.025  CH1130675676  A3GWD4       EUR         ALTSEUR SE                  NaN                NaN            NaN          NaN              NaN         NaN             NaN              NaN
50        21Shares Crypto Mid-Cap Index ETP   0.025  CH1130675676  A3GWD4       USD            ALTS SE                  NaN                NaN            NaN          NaN              NaN         NaN             NaN              NaN
51                                   Shorts                                                                                                                                             NaN
52               21Shares Short Bitcoin ETP   0.025  CH0514065058  A2781V       EUR                                 2SBT GY                           SBTC FP                           NaN                     2SBT GS          2SBT GD
53               21Shares Short Bitcoin ETP   0.025  CH0514065058  A2781V       USD            SBTC SE                                 SBTC NA                                          NaN

In [86]:
df_template = pd.read_excel('Template pre-trade analysis.xlsx', usecols="A:I",
                   sheet_name = "Sheet1",
                   engine='openpyxl')

In [99]:
name = df_template[df_template['Unnamed: 0']=='Name']['Unnamed: 1'].to_list()[0]

In [172]:
name

'21Shares Bitcoin ETP'

In [100]:
isin = df[df['Product / Underlying']== name]['ISIN'].to_list()[0]

In [115]:
isin

'CH0454664001'

In [ ]:
df_template

In [137]:
df_template[df_template['Unnamed: 0']=='ISIN']['Unnamed: 1']

8    NaN
Name: Unnamed: 1, dtype: object

In [126]:
df_template

                         Unnamed: 0            Unnamed: 1 Unnamed: 2              Unnamed: 3  Unnamed: 4             Unnamed: 5  Unnamed: 6 Unnamed: 7  Unnamed: 8
0                               NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
1                               NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
2                               NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
3   Pre-trade analysis - 28.04.2022                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
4                               NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
5              Ø Details of the ETP                   NaN        NaN                     NaN         NaN  Ø Primary market data         NaN        NaN         NaN
6                               NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
7                              Name  21Shares Bitcoin ETP        NaN                     NaN         NaN      Primary  Exchange         NaN        SIX         NaN
8                              ISIN                   NaN        NaN                     NaN         NaN                 Ticker         NaN      ABTC          NaN
9                               TER                   NaN        NaN                     NaN         NaN         Inception date         NaN        NaN         NaN
10                             Type          Single Asset        NaN                     NaN         NaN               Last NAV         NaN        NaN         NaN
11                       Underlying               Bitcoin        NaN                     NaN         NaN                    AUM         NaN        NaN         NaN
12                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
13                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
14            Ø Trading information                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
15                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
16                         Exchange                   NaN     Ticker                Currency         NaN                    NaN         NaN        NaN         NaN
17                              SIX                   NaN       ABTC  USD, EUR,CHF, JPY, GBP         NaN                    NaN         NaN        NaN         NaN
18                   Euronext Paris                   NaN       ABTC                     EUR         NaN                    NaN         NaN        NaN         NaN
19               Euronext Amsterdam                   NaN       ABTC                     USD         NaN                    NaN         NaN        NaN         NaN
20                            Xetra                   NaN       2BTC                EUR, USD         NaN                    NaN         NaN        NaN         NaN
21                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
22                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
23             Ø Liquidity analysis                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
24                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
25         20D daily average spread                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
26       Primary market turnover 1M                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
27     Secondary market turnover 1M                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
28              Underlying turnover                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
29          Desired amount to trade                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
30       % wrt underlying liquidity                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
31                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
32                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
33             Ø Indicative pricing                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
34                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
35                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
36                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
37                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
38                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
39                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
40                       Ø Comments                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
41                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
42                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
43                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
44                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
45                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
46                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
47                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
48                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
49                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
50                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
51                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
52                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
53                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
54                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
55                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
56                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
57                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
58                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
59                       Disclaimer                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN

In [134]:
df_template

                         Unnamed: 0            Unnamed: 1 Unnamed: 2              Unnamed: 3  Unnamed: 4             Unnamed: 5  Unnamed: 6 Unnamed: 7  Unnamed: 8
0                               NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
1                               NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
2                               NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
3   Pre-trade analysis - 28.04.2022                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
4                               NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
5              Ø Details of the ETP                   NaN        NaN                     NaN         NaN  Ø Primary market data         NaN        NaN         NaN
6                               NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
7                              Name  21Shares Bitcoin ETP        NaN                     NaN         NaN      Primary  Exchange         NaN        SIX         NaN
8                              ISIN                   NaN        NaN                     NaN         NaN                 Ticker         NaN      ABTC          NaN
9                               TER                   NaN        NaN                     NaN         NaN         Inception date         NaN        NaN         NaN
10                             Type          Single Asset        NaN                     NaN         NaN               Last NAV         NaN        NaN         NaN
11                       Underlying               Bitcoin        NaN                     NaN         NaN                    AUM         NaN        NaN         NaN
12                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
13                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
14            Ø Trading information                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
15                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
16                         Exchange                   NaN     Ticker                Currency         NaN                    NaN         NaN        NaN         NaN
17                              SIX                   NaN       ABTC  USD, EUR,CHF, JPY, GBP         NaN                    NaN         NaN        NaN         NaN
18                   Euronext Paris                   NaN       ABTC                     EUR         NaN                    NaN         NaN        NaN         NaN
19               Euronext Amsterdam                   NaN       ABTC                     USD         NaN                    NaN         NaN        NaN         NaN
20                            Xetra                   NaN       2BTC                EUR, USD         NaN                    NaN         NaN        NaN         NaN
21                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
22                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
23             Ø Liquidity analysis                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
24                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
25         20D daily average spread                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
26       Primary market turnover 1M                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
27     Secondary market turnover 1M                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
28              Underlying turnover                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
29          Desired amount to trade                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
30       % wrt underlying liquidity                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
31                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
32                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
33             Ø Indicative pricing                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
34                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
35                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
36                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
37                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
38                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
39                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
40                       Ø Comments                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
41                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
42                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
43                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
44                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
45                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
46                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
47                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
48                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
49                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
50                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
51                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
52                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
53                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
54                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
55                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
56                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
57                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
58                              NaN                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN
59                       Disclaimer                   NaN        NaN                     NaN         NaN                    NaN         NaN        NaN         NaN

In [88]:
df_template.to_excel('test.xlsx',index=False,header=False)

In [4]:
pd.read_excel('Template pre-trade analysis.xlsx',skiprows=[1,2,3,4])

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ø Details of the ETP,NaN,NaN,NaN,NaN,Ø Primary market data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Name,21Shares Bitcoin ETP,NaN,NaN,NaN,Primary Exchange,NaN,SIX,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ISIN,NaN,NaN,NaN,NaN,Ticker,NaN,ABTC,NaN,NaN,NaN,"Details of the ETP from Grafana, primary marke...",NaN,NaN,NaN
5,TER,NaN,NaN,NaN,NaN,Inception date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Type,Single Asset,NaN,NaN,NaN,Last NAV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Underlying,Bitcoin,NaN,NaN,NaN,AUM,NaN,NaN,NaN,NaN,NaN,From Grafana,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Ø Trading information,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Exchange,NaN,Ticker,Currency,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,SIX,NaN,ABTC,"USD, EUR,CHF, JPY, GBP",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Euronext Paris,NaN,ABTC,EUR,NaN,NaN,NaN,NaN,NaN,NaN,Website?,NaN,NaN,NaN,NaN
15,Euronext Amsterdam,NaN,ABTC,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Xetra,NaN,2BTC,"EUR, USD",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Ø Liquidity analysis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,20D daily average spread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,From Bbg,NaN,NaN,NaN,NaN
22,Primary market turnover 1M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Secondary market turnover 1M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Underlying turnover,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,From CoinGeko in $Bn,NaN,NaN,NaN,NaN
25,Desired amount to trade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manual input,NaN,NaN,NaN,NaN
26,% wrt underlying liquidity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D32/D31 in percentage,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chart of the historical spread or turnover
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Ø Indicative pricing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manual input,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Ø Comments,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,If the desired amount is below $25M:,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Up to a size of (cell D31) which represents (c...,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"If cell C12=""single asset""",NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The underlying liquidity for (cell C13) is (ce...,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,For a (cell D31) trade at (manual input if at ...,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Disclaimer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [156]:
df_temp

     0   1   2   3   4   5
0  NaN NaN NaN NaN NaN NaN
1  NaN NaN NaN NaN NaN NaN
2  NaN NaN NaN NaN NaN NaN
3  NaN NaN NaN NaN NaN NaN
4  NaN NaN NaN NaN NaN NaN
5  NaN NaN NaN NaN NaN NaN
6  NaN NaN NaN NaN NaN NaN
7  NaN NaN NaN NaN NaN NaN
8  NaN NaN NaN NaN NaN NaN
9  NaN NaN NaN NaN NaN NaN
10 NaN NaN NaN NaN NaN NaN
11 NaN NaN NaN NaN NaN NaN
12 NaN NaN NaN NaN NaN NaN
13 NaN NaN NaN NaN NaN NaN
14 NaN NaN NaN NaN NaN NaN
15 NaN NaN NaN NaN NaN NaN
16 NaN NaN NaN NaN NaN NaN
17 NaN NaN NaN NaN NaN NaN
18 NaN NaN NaN NaN NaN NaN
19 NaN NaN NaN NaN NaN NaN

In [170]:
df_temp.iloc[2:5,2:5] = y

In [169]:
y = pd.DataFrame(np.reshape([11,12,13]*3,(3,3)))

In [171]:
df_temp

     0   1     2     3     4   5
0  NaN NaN   NaN   NaN   NaN NaN
1  NaN NaN   NaN   NaN   NaN NaN
2  NaN NaN  11.0  12.0  13.0 NaN
3  NaN NaN  11.0  12.0  13.0 NaN
4  NaN NaN  11.0  12.0  13.0 NaN
5  NaN NaN   NaN   NaN   NaN NaN
6  NaN NaN   NaN   NaN   NaN NaN
7  NaN NaN   NaN   NaN   NaN NaN
8  NaN NaN   NaN   NaN   NaN NaN
9  NaN NaN   NaN   NaN   NaN NaN
10 NaN NaN   NaN   NaN   NaN NaN
11 NaN NaN   NaN   NaN   NaN NaN
12 NaN NaN   NaN   NaN   NaN NaN
13 NaN NaN   NaN   NaN   NaN NaN
14 NaN NaN   NaN   NaN   NaN NaN
15 NaN NaN   NaN   NaN   NaN NaN
16 NaN NaN   NaN   NaN   NaN NaN
17 NaN NaN   NaN   NaN   NaN NaN
18 NaN NaN   NaN   NaN   NaN NaN
19 NaN NaN   NaN   NaN   NaN NaN

In [178]:
df_1 = pd.DataFrame({'Name':['Name','ISIN','TER','Type','Underlying'],
             'Info': [name,isin,float('NaN'),'Single Asset','Bitcoin']
             })

In [179]:
df_1

         Name                  Info
0        Name  21Shares Bitcoin ETP
1        ISIN          CH0454664001
2         TER                   NaN
3        Type          Single Asset
4  Underlying               Bitcoin

In [196]:
ex = df[(df['Product / Underlying']==name) & (df['Currency']=='USD')]['SIX Swiss Exchange'].to_list()[0].split()[0]

In [198]:
df_2 = pd.DataFrame({'Name':['Primary  Exchange','Ticker','Inception date','Last NAV','AUM'],
             'Info': ['SIX',ex,float('NaN'),float('NaN'),float('NaN')]
             })

In [199]:
df_2

                Name  Info
0  Primary  Exchange   SIX
1             Ticker  ABTC
2     Inception date   NaN
3           Last NAV   NaN
4                AUM   NaN

In [253]:
d = df[df['Product / Underlying']==name][list(df)[5:]].T

In [254]:
d = d.fillna(' ')

In [255]:
d

                              10          11          12       13       14
SIX Swiss Exchange    ABTCCHF SE  ABTCEUR SE  ABTCGBP SE  ABTC SE
Deutsche Börse Xetra                 2BTC GY
Euronext Amsterdam                                        ABTC NA
Euronext Paris                       ABTC FP
Wiener Börse                         ABTC AV
Nasdaq Stockholm                                                   ABTC SS
BX Swiss              ABTCCHF BW
Börse Stuttgart                      2BTC GS
Börse Düsseldorf                     2BTC GD

In [256]:
d = d[[10,11,12,13,14]].agg('-'.join, axis=1)

In [257]:
d = pd.DataFrame(d)

In [274]:
def f(x):
    x = x.split('-')
    x = [i[:4] for i in x if i.strip()!='']
    x = set(x)
    
    return list(x)[0]

In [309]:
d = d[0].apply(lambda x:f(x))

In [280]:
t = df[df['Product / Underlying']==name][list(df)[4:]]

In [284]:
t.set_index('Currency', inplace=True)

In [288]:
t = t.fillna(' ')
t = t.agg('-'.join, axis=1)

In [291]:
t = t.apply(lambda x:f(x))

In [304]:
t = t.to_dict()

In [307]:
tt = {}
for k,v in t.items():
    if v not in tt:
        tt[v] = [k]
    else:
        tt[v].append(k)

In [308]:
tt

{'ABTC': ['CHF', 'GBP', 'USD', 'SEK'], '2BTC': ['EUR']}

In [312]:
d = pd.DataFrame(d)

In [317]:
d[1] = d[0].apply(lambda x: ','.join(tt[x]))

In [320]:
d.reset_index(inplace=True)

In [322]:
df_3 = d

In [323]:
df_3

                  index     0                1
0    SIX Swiss Exchange  ABTC  CHF,GBP,USD,SEK
1  Deutsche Börse Xetra  2BTC              EUR
2    Euronext Amsterdam  ABTC  CHF,GBP,USD,SEK
3        Euronext Paris  ABTC  CHF,GBP,USD,SEK
4          Wiener Börse  ABTC  CHF,GBP,USD,SEK
5      Nasdaq Stockholm  ABTC  CHF,GBP,USD,SEK
6              BX Swiss  ABTC  CHF,GBP,USD,SEK
7       Börse Stuttgart  2BTC              EUR
8      Börse Düsseldorf  2BTC              EUR

In [326]:
len(df_1) + len(df_2) + len(df_3)

19

In [363]:
import numpy as np
x = np.reshape([float('NaN')]*300,(50,6))
df_temp = pd.DataFrame(x)

In [364]:
row = df_1.shape[0]
col = df_1.shape[1]

In [381]:
df_temp.iloc[0:1 ,2:3] = ['Pre-trade analysis - 28.04.2022']

In [380]:
df_temp.iloc[1:2 ,1:2] = ['Details of the ETP']

In [365]:
df_temp.iloc[2:2+row,1:1+col] = df_1

In [366]:
row1 = df_2.shape[0]
col1 = df_2.shape[1]

In [382]:
df_temp.iloc[4+row: 5+row ,1:2] = ['Primary market data']

In [367]:
df_temp.iloc[4+row: 4+row+row1 ,1:1+col1] = df_2

In [368]:
row2 = df_3.shape[0]
col2 = df_3.shape[1]

In [378]:
df_temp.iloc[5+row+row1: 6+row+row1 ,1:2] = ['Trading information']

In [369]:
df_temp.iloc[6+row+row1: 7+row+row1 ,1:1+col2] = ['Exchange','Ticker','Currency']

In [370]:
df_temp.iloc[7+row+row1: 7+row+row1+row2 ,1:1+col2] = df_3

In [375]:
df_temp.iloc[9+row+row1+row2: 10+row+row1+row2 ,1:2] = ['Liquidity analysis']

In [373]:
df_temp.iloc[10+row+row1+row2: 16+row+row1+row2 ,1:2] = ['20D daily average spread',
'Primary market turnover 1M',
'Secondary market turnover 1M',
'Underlying turnove',
'Desired amount to trade',
'% wrt underlying liquidity',]

In [371]:
df_temp.to_excel('newfile.xlsx',index=False,header=False)

In [383]:
df_temp

     0                             1                                2                3   4   5
0  NaN                           NaN  Pre-trade analysis - 28.04.2022              NaN NaN NaN
1  NaN            Details of the ETP                              NaN              NaN NaN NaN
2  NaN                          Name             21Shares Bitcoin ETP              NaN NaN NaN
3  NaN                          ISIN                     CH0454664001              NaN NaN NaN
4  NaN                           TER                              NaN              NaN NaN NaN
5  NaN                          Type                     Single Asset              NaN NaN NaN
6  NaN                    Underlying                          Bitcoin              NaN NaN NaN
7  NaN                           NaN                              NaN              NaN NaN NaN
8  NaN                           NaN                              NaN              NaN NaN NaN
9  NaN           Primary market data                              SIX              NaN NaN NaN
10 NaN                        Ticker                             ABTC              NaN NaN NaN
11 NaN                Inception date                              NaN              NaN NaN NaN
12 NaN                      Last NAV                              NaN              NaN NaN NaN
13 NaN                           AUM                              NaN              NaN NaN NaN
14 NaN                           NaN                              NaN              NaN NaN NaN
15 NaN           Trading information                              NaN              NaN NaN NaN
16 NaN                      Exchange                           Ticker         Currency NaN NaN
17 NaN            SIX Swiss Exchange                             ABTC  CHF,GBP,USD,SEK NaN NaN
18 NaN          Deutsche Börse Xetra                             2BTC              EUR NaN NaN
19 NaN            Euronext Amsterdam                             ABTC  CHF,GBP,USD,SEK NaN NaN
20 NaN                Euronext Paris                             ABTC  CHF,GBP,USD,SEK NaN NaN
21 NaN                  Wiener Börse                             ABTC  CHF,GBP,USD,SEK NaN NaN
22 NaN              Nasdaq Stockholm                             ABTC  CHF,GBP,USD,SEK NaN NaN
23 NaN                      BX Swiss                             ABTC  CHF,GBP,USD,SEK NaN NaN
24 NaN               Börse Stuttgart                             2BTC              EUR NaN NaN
25 NaN              Börse Düsseldorf                             2BTC              EUR NaN NaN
26 NaN                           NaN                              NaN              NaN NaN NaN
27 NaN                           NaN                              NaN              NaN NaN NaN
28 NaN            Liquidity analysis                              NaN              NaN NaN NaN
29 NaN      20D daily average spread                              NaN              NaN NaN NaN
30 NaN    Primary market turnover 1M                              NaN              NaN NaN NaN
31 NaN  Secondary market turnover 1M                              NaN              NaN NaN NaN
32 NaN            Underlying turnove                              NaN              NaN NaN NaN
33 NaN       Desired amount to trade                              NaN              NaN NaN NaN
34 NaN    % wrt underlying liquidity                              NaN              NaN NaN NaN
35 NaN                           NaN                              NaN              NaN NaN NaN
36 NaN                           NaN                              NaN              NaN NaN NaN
37 NaN                           NaN                              NaN              NaN NaN NaN
38 NaN                           NaN                              NaN              NaN NaN NaN
39 NaN                           NaN                              NaN              NaN NaN NaN
40 NaN                           NaN                              NaN              NaN NaN NaN
41 NaN                           NaN                              NaN              NaN NaN NaN
42 NaN                           NaN                              NaN              NaN NaN NaN
43 NaN                           NaN                              NaN              NaN NaN NaN
44 NaN                           NaN                              NaN              NaN NaN NaN
45 NaN                           NaN                              NaN              NaN NaN NaN
46 NaN                           NaN                              NaN              NaN NaN NaN
47 NaN                           NaN                              NaN              NaN NaN NaN
48 NaN                           NaN                              NaN              NaN NaN NaN
49 NaN                           NaN                              NaN              NaN NaN NaN