In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('TDMX_DOCUMENT_S_9501.csv')
df2 = pd.read_excel('TDMX_DOCUMENTS_S_9501_UI.xlsx')

In [3]:
df1.head()

,Unnamed: 0,object_id,class_id,tdmx_id,tdm_archive_name,revision,state,creation_date,user_object_id,user_id_mod,...,cn_acs_tded_exch_contact,cn_acs_tded_exch_support,cn_acs_tded_exch_job_id,tdm_site_id,tdm_site_id_mod,tdm_site_id_owner,cn_acs_document_related_ite1,cn_acs_document_related_ite2,cn_acs_document_related_ite3,cn_acs_document_related_ite4
0,61186,2258633,395,DOC-0096187,,A.1,1,27-01-2020 15:05,1452,1,...,-2147483647,-2147483647,,1,1,1,-2147483647,-2147483647,-2147483647,-2147483647
1,406372,1219415,117,PRT-0035214,,A,3,26-03-2015 12:51,2411,1,...,-2147483647,-2147483647,,1,1,1,-2147483647,-2147483647,-2147483647,-2147483647
2,610148,2062417,117,PRT-0042931,,D,3,11-07-2019 09:55,4325,4325,...,-2147483647,-2147483647,,1,1,1,-2147483647,-2147483647,-2147483647,-2147483647
3,621954,2070232,117,PRT-0045282,,B,3,18-01-2019 10:48,2835,1,...,-2147483647,-2147483647,,1,1,1,-2147483647,-2147483647,-2147483647,-2147483647
4,647763,2383764,117,PRT-0052721,,B.2,1,11-01-2021 13:39,69,69,...,-2147483647,-2147483647,,1,1,1,-2147483647,-2147483647,-2147483647,-2147483647

In [4]:
df2.head()

,objectid,description,revision,creation date,state
0,TDEP-0014389A-A,2112140933_6599_DRW-0013176 - SUNROOF_-_TLOR-2D-,A,2021-12-14 10:52:00,Released
1,TDEP-0014389,2112140933_6599_DRW-0013176 - SUNROOF_-_TLOR-2D-,A,2021-12-14 10:33:00,Released
2,TDEP-0013842A-B,2109281730_6599_CLEVIS_-_ASSEMBLED-,A,2021-09-28 17:47:00,Released
3,TDEP-0013842A-A,2109281730_6599_CLEVIS_-_ASSEMBLED-,A,2021-09-28 17:46:00,Released
4,TDEP-0013842,2109281730_6599_CLEVIS_-_ASSEMBLED-,A,2021-09-28 17:30:00,Released

In [5]:
df1_match = set()
df2_match = set()
for index1, row1 in df1.iterrows():
    for index2, row2 in df2.iterrows():
        if row1['tdmx_id'] == row2['objectid'] and row1['revision'] == row2['revision']:
            df1_match.add(index1)
            df2_match.add(index2)

In [6]:
df1_non_match = set(df1.index)-df1_match
df2_non_match = set(df2.index)-df2_match

In [7]:
df1.iloc[list(df1_match)].to_csv('MATCH_TDMX_DOCUMENT_S_9501.csv')
df1.iloc[list(df1_non_match)].to_csv('NONMATCH_TDMX_DOCUMENT_S_9501.csv')

df2.iloc[list(df2_match)].to_csv('MATCH_TDMX_DOCUMENTS_S_9501_UI.csv')
df2.iloc[list(df2_non_match)].to_csv('NON_MATCH_TDMX_DOCUMENTS_S_9501_UI.csv')